server:
  port: 9001
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
  ssl:
    key-store: classpath:/key/keystore.p12
    key-store-type: PKCS12
    key-store-password: khb0915

spring:
  application:
    name: koke_backend
  config:
    activate:
      on-profile: master
  devtools:
    restart:
      enabled: true
  datasource:
    url: ENC(hKRHN9cc7mGICw0GzAKT6XaDZJjd5omviV7fXp9gVhN79odVeU9IjcJhiDZrXw9oG8m4gEHDrEYZNpbVsxCDbwbo+ggNHWZpNow3nyOCtN/zttzbs4L0ouQ33hIyV7LqyMBR0OpFqfR4K2l5pr6H4w==)
    username: ENC(UHlF351brOUFhxWrkrrB/ds9xQaPlanX3pXME6o3Rbs=)
    password: ENC(Zi1Wzawi+DVlzHYGOdYRzagyGfdtb6mL/IV12Mzl9Xw=)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      metadata_builder_contributor: com.koke.koke_backend.module.jpa.SqlFunctionsMetadataBuilderContributor
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: koke-redis-001.phbkid.0001.apn2.cache.amazonaws.com
      port: 6379
      database: 0
      username:
      password:
jwt:
  accessTokenValidity: 14d
  refreshTokenValidity: 1M
  secret: YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=

springdoc:
  model-and-view-allowed: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    default-models-expand-depth: -1
  enable-native-support: true

logging:
  config: classpath:logback-spring.xml
  charset:
    console: UTF-8
    file: UTF-8

custom:
  path: '/home/ubunutu/koke_file'
