spring:
  application:
    name: koke_backend
  devtools:
    restart:
      enabled: true
  datasource:
    url: ENC(hKRHN9cc7mGICw0GzAKT6XaDZJjd5omviV7fXp9gVhN79odVeU9IjcJhiDZrXw9oG8m4gEHDrEYZNpbVsxCDbwbo+ggNHWZpNow3nyOCtN/zttzbs4L0ouQ33hIyV7LqyMBR0OpFqfR4K2l5pr6H4w==)
    username: ENC(UHlF351brOUFhxWrkrrB/ds9xQaPlanX3pXME6o3Rbs=)
    password: ENC(Zi1Wzawi+DVlzHYGOdYRzagyGfdtb6mL/IV12Mzl9Xw=)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    activate:
      on-profile: master
  data:
    redis:
      host: ENC(ygmbC+pwseqZ8gFoPJLtGHBzUD31ofcEnuIeZ/C+zqiRDxpViccLtXklecKy27e+ATePEFA2nk4eEdCi3ABX/Va7dGTzmKT9F5n0Nx93jhQ=)
      port: 6379
      database: 0
      password:
  security:
    oauth2.client:
      registration:
        google:
          clientId: ENC(Opoo9OrktGzMbUh6jxDJv+urs1bSztwyByEmcZx2HJRt3kVgSdWVc7eepNLsfZySQ/EH8O5hSA8P/25u9KYLz0Tyd/l1xavrxJVXgH5dSPHSMIEsyLKthrG0F0PsXaiN)
          clientSecret: ENC(adR2s183Qd/+yFsAf+5gar13tx29wXh/uQ2IFHqw+/LrAJy7F4xPk3B4LGkLgpXz9XEHH9ghSPBaKdPDdMc2mw==)
          scope:
            - email
            - profile
        naver:
          clientId: ENC(F9rbZISjUIS2FUwV/3l7Npp+HkA3WHHhYwvfKf7UcsVKhgpjJVe/D/bNbU2C7Ree)
          clientSecret: ENC(hZr/XZfMDKDSVcgLKr6dVdEV1XNMqXwcw/ObBt5XZ2M=)
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          scope:
            - nickname
            - email
            - profile_image
          clientName: Naver
        kakao:
          clientId: ENC(u/UaXouMRjGiTyNtjdMleZHn3abae+TyEM1ha34X1MR6GRUluTVcJFmTkzndKqip04aXJJbmAtspAt7xBvy4sw==)
          clientSecret: ENC(1ukLqdPf4k+jfVVf4GjHRKtmbjZ9lo/909wajaKT8M31X85n1Xdsg+SFAr/C2FlGidqNIIwkRTAR2DP+ggsdeQ==)
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          scope:
            - profile_nickname
            - profile_image
            - account_email
          clientName: Kakao
      # Provider 설정
      provider:
        naver:
          authorizationUri: https://nid.naver.com/oauth2.0/authorize
          tokenUri: https://nid.naver.com/oauth2.0/token
          userInfoUri: https://openapi.naver.com/v1/nid/me
          userNameAttribute: response
        kakao:
          authorizationUri: https://kauth.kakao.com/oauth/authorize
          tokenUri: https://kauth.kakao.com/oauth/token
          userInfoUri: https://kapi.kakao.com/v2/user/me
          userNameAttribute: id
jwt:
  accessTokenValidity: 14d
  refreshTokenValidity: 1M
  secret: YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=
springdoc:
  model-and-view-allowed: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: rest-api-doc.html
    default-models-expand-depth: -1

logging:
  config: classpath:logback-spring.xml
  charset:
    console: UTF-8
    file: UTF-8
custom:
  path: '/home/ubunutu/koke_file'

server:
  port: 9001
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto

---

spring:
  application:
    name: koke_backend
  devtools:
    restart:
      enabled: true
  datasource:
    url: ENC(BzzU8Z8hG3BL3y50gl7SBCdNbIx/pB4HoslUGBeFCUFLf5QCYYbhZwtYrdNgPM/31U4O5gbluhh8ltOVAGTJfJ3EOYFT0x+raQ6d7k9Iq7wWsZCDH/4mO+6XlN0v9bJCkcbrwyIz/zBETgNCvAj8kw==)
    username: ENC(UHlF351brOUFhxWrkrrB/ds9xQaPlanX3pXME6o3Rbs=)
    password: ENC(Zi1Wzawi+DVlzHYGOdYRzagyGfdtb6mL/IV12Mzl9Xw=)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    activate:
      on-profile: develop
  data:
    redis:
      host: ENC(ygmbC+pwseqZ8gFoPJLtGHBzUD31ofcEnuIeZ/C+zqiRDxpViccLtXklecKy27e+ATePEFA2nk4eEdCi3ABX/Va7dGTzmKT9F5n0Nx93jhQ=)
      port: 6379
      database: 1
      password:
  security:
    oauth2.client:
      registration:
        google:
          clientId: ENC(Opoo9OrktGzMbUh6jxDJv+urs1bSztwyByEmcZx2HJRt3kVgSdWVc7eepNLsfZySQ/EH8O5hSA8P/25u9KYLz0Tyd/l1xavrxJVXgH5dSPHSMIEsyLKthrG0F0PsXaiN)
          clientSecret: ENC(adR2s183Qd/+yFsAf+5gar13tx29wXh/uQ2IFHqw+/LrAJy7F4xPk3B4LGkLgpXz9XEHH9ghSPBaKdPDdMc2mw==)
          scope:
            - email
            - profile
        naver:
          clientId: ENC(F9rbZISjUIS2FUwV/3l7Npp+HkA3WHHhYwvfKf7UcsVKhgpjJVe/D/bNbU2C7Ree)
          clientSecret: ENC(hZr/XZfMDKDSVcgLKr6dVdEV1XNMqXwcw/ObBt5XZ2M=)
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          scope:
            - nickname
            - email
            - profile_image
          clientName: Naver
        kakao:
          clientId: ENC(u/UaXouMRjGiTyNtjdMleZHn3abae+TyEM1ha34X1MR6GRUluTVcJFmTkzndKqip04aXJJbmAtspAt7xBvy4sw==)
          clientSecret: ENC(1ukLqdPf4k+jfVVf4GjHRKtmbjZ9lo/909wajaKT8M31X85n1Xdsg+SFAr/C2FlGidqNIIwkRTAR2DP+ggsdeQ==)
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          scope:
            - profile_nickname
            - profile_image
            - account_email
          clientName: Kakao
      # Provider 설정
      provider:
        naver:
          authorizationUri: https://nid.naver.com/oauth2.0/authorize
          tokenUri: https://nid.naver.com/oauth2.0/token
          userInfoUri: https://openapi.naver.com/v1/nid/me
          userNameAttribute: response
        kakao:
          authorizationUri: https://kauth.kakao.com/oauth/authorize
          tokenUri: https://kauth.kakao.com/oauth/token
          userInfoUri: https://kapi.kakao.com/v2/user/me
          userNameAttribute: id
jwt:
  accessTokenValidity: 14d
  refreshTokenValidity: 1M
  secret: YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=
springdoc:
  model-and-view-allowed: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: rest-api-doc.html
    default-models-expand-depth: -1

logging:
  config: classpath:logback-spring.xml
  charset:
    console: UTF-8
    file: UTF-8
custom:
  path: '/home/ubuntu/koke_file_test'

server:
  port: 9001
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto

